config/routes.rb
EmergenChef::Application.routes.draw do
  require 'sidekiq/web'
=begin
  delete 'destroy_order' => 'orders#destroy', :as => :destroy_order_path
  post 'orders' => 'orders#create'
  update method
=end

  root 'users#welcome'
  get "about/adam" => "statics#adam", :as => :adam
  get 'sign_up' => 'users#new', :as => :new_user
  delete 'sign_out' => 'auths#destroy', :as => :auths
  get 'sign_in' => 'auths#new', :as => :new_auth
  get 'auths/resend-email/:id' => 'auths#resend_verification_email', :as => :resend
  resources :auths, only:[ :create]
  
  get 'users/:id/verify/:verification_token' => 'users#verify', :as => :verify_user
  patch 'users/:id' => 'users#update'
  resources :users, except:[:new, :update] do
    resources :orders do
    end
  end  
  
  mount Sidekiq::Web => '/sidekiq'

end

app/models/order.rb
class Order
  include Mongoid::Document
  field :name, type: String
  field :party_size, type: Integer
  field :dietary_preferences, type: String
  field :address, type: String
  field :emergency_date, type: Date
  field :reason_for_event, type: String
  belongs_to :user

  validates_presence_of :name
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order_and_user, only: [:show, :alert, :edit, :update, :destroy]
  before_action :set_user_only, only: [:new, :create]
  before_action :login_required

  #orders are predicated on user page, which is predicated on params; page can only be accessed by admin or by matching current_user
  def index
    @user = User.find(params[:user_id])
    @orders = User.find(params[:user_id]).orders
  end

  #action for declaring a new order's attributes
  def new
    @order = Order.new

  end

  #action for showing an order's details
  def show
  end

  #action for creating a new order
  def create
    #set order and user differs slightly from majority of actions
    @order = Order.new(order_params)
    if @order.save
      @this_user.orders.push(@order)
      redirect_to @this_user, notice: "Order saved"
    else
      render action: 'new'
    end
  end

  #action for e-mailing an order to the EmergenChef
  def alert
    Confirmer.delay.emergency(@order.id, @this_user.id)
    redirect_to @this_user
    flash[:notice] = "Email on route!"
  end

  #action for editing an order
  def edit
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @this_user, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    redirect_to @this_user
  end

  private
    def set_order_and_user
      @order = Order.find(params[:id]) #order id, not user id
      @this_user = User.find(params[:user_id])
    end

    def set_user_only
      @this_user = User.find(params[:user_id])
    end

    def order_params
      params.require(:order).permit(:name, :party_size, :dietary_preferences, :address, :emergency_date, :reason_for_event)
    end
    
    def login_required
      unless current_user
        redirect_to new_auth_path
      end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="row">
  <div class='col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1'>
    <p><%= link_to 'Back to Dashboard', @this_user %></p>
  </div>
</div>
<div class="row">
  <div class = "well col-md-offset-2 col-md-8 col-sm-8 col-sm-offset-2 col-xs-offset-2 col-xs-8">
    <fieldset>
      <legend><%= params[:action] == "edit" ? "Edit #{@order.name}" : "Create an Order" %></legend>
      <%= form_for [@this_user, @order] do |o| %>
        <% if @order.errors.any? %>
          <div id = "error_explanation">
            <h4>Your order <%= pluralize(@order.errors.count,"error") %> prohibited this order from being saved</h4>
            <ul>
              <% @order.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class = "field form-group clearfix">
          <div class = "col-md-12"><%= o.label :post, "Name of Order*" %></div>
          <div class = "col-md-12"><%= o.text_field :name, class: "form-control" %></div>
        </div>
        <div class = "field form-group clearfix">
          <div class = "col-md-12"><%= o.label :post, "Date (when are we cooking?)" %></div>
          <div class = "col-md-12"><%= o.date_select :emergency_date, {:order => [:day, :month, :year]}, {:class=> "col-md-4 form-control"}%></div>
        </div>
        <div class = "field form-group clearfix">
          <div class = "col-md-12"><%= o.label :post, "Address (where are we cooking?)" %></div>
          <div class = "col-md-12"><%= o.text_area :address, class: "form-control"%></div>
        </div>

        <div class = "field form-group clearfix">
          <div class = "col-md-12"><%= o.label :post, "Does your Team have any Dietary Preferences?" %></div>
          <div class = "col-md-12"><%= o.text_field :dietary_preferences, class: "form-control diet" %></div>
        </div>
        <div class = "form-group clearfix">
          <div class = "col-md-12"><%= o.label :party_size %></div>
          <div class = "col-md-12"><%= o.number_field :party_size, class: "form-control" %></div>
        </div>
        <div class = "form-group clearfix">
          <div class = "col-md-12"><%= o.label :reason_for_event %></div>
          <div class = "col-md-12"><%= o.text_area :reason_for_event, class: "form-control" %></div>
        </div>
        <div class = "actions">
          <%= o.submit class: "btn btn-primary"%>
        </div>

      <% end %>
    </fieldset>
  </div>
</div>

<div class="row">
  <div class='col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1'>
    <%= link_to 'Back to Dashboard', @this_user %>
  </div>
</div>

app/views/orders/_index.html.erb
<h2>Orders <small>| <%= link_to 'New Order', new_user_order_path(id) %></small></h2>
<ul id="orders">
  <% @orders.each do |o| %>
    <li class="order">
      <ul>
        <li>
         <%= link_to "#{o.name}", user_order_path(id, o.id) %> 
        </li>
        <li>
         <%= link_to "Edit", edit_user_order_path(id, o.id) %>
        </li>
        <li>
         <%= link_to 'delete', user_order_path(id,o.id), {method: :delete} %>
        </li>
        <li>
         <%= button_to "Tonight", user_order_path(id,o.id), {method: :post, class: "btn btn-danger"} %>
        </li>
      </ul>
    </li>
  <% end %>
</ul>

app/views/orders/edit.html.erb
<%= render 'form' %>

app/views/orders/new.html.erb
<%= render 'form' %>

app/views/orders/show.html.erb
<div class="row">
  <h1 class= 'col-md-9 col-md-offset-3 col-sm-10 col-sm-offset-2 col-xs-11 col-xs-offset-1'>Viewing order "<%= @order.name %>"</h1>
  <div class="col-md-6 col-md-offset-4 col-sm-8 col-sm-offset-3 col-xs-10 col-xs-offset-2">
    <ul>
      <li>Party Size: <%= @order.party_size %></li>
      <li>Dietary Preferences: <%= @order.dietary_preferences %></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class='col-md-9 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1'>
    <p><%= link_to 'Back to Dashboard', @this_user %></p>
  </div>
</div>