config/routes.rb
EmergenChef::Application.routes.draw do
  require 'sidekiq/web'
=begin
  delete 'destroy_order' => 'orders#destroy', :as => :destroy_order_path
  post 'orders' => 'orders#create'
  update method
=end

  root 'users#welcome'
  get "about/adam" => "statics#adam", :as => :adam
  get 'sign_up' => 'users#new', :as => :new_user
  delete 'sign_out' => 'auths#destroy', :as => :auths
  get 'sign_in' => 'auths#new', :as => :new_auth
  get 'auths/resend-email/:id' => 'auths#resend_verification_email', :as => :resend
  resources :auths, only:[ :create]
  
  get 'users/:id/verify/:verification_token' => 'users#verify', :as => :verify_user
  patch 'users/:id' => 'users#update'
  resources :users, except:[:new, :update] do
    resources :orders do
    end
  end  
  
  mount Sidekiq::Web => '/sidekiq'

end

app/views/confirmer/emergency.html.erb
    <div width = "390px" height = "180px" style = "background-color:#911821; border:2px solid black">
      <%= image_tag 'http://storage.googleapis.com/emergenchefvideo/logo.png' %>
    </div>
    <div style = "border:2px solid black; border-top:0; padding:1em">
      <h1><%= @account.profile.startup_name %> Needs an Emergen-Chef Tonight!</h1>
      <h2>User Info:</h2>
        <ul>
          <li><strong>Name:</strong> <%= @account.profile.startup_name %></li>
          <li><strong>Email:</strong> <%= @account.email_address %></li>
          <li><strong>User Address:</strong> <%= @account.profile.address %></li>
          <li><strong>Phone Number:</strong> <%= @account.profile.phone_number %></li>
          <li><strong>Frequency of All Nighters:</strong> <%= @account.profile.how_frequently_your_team_pulls_all_nighters %></li>
          <li><strong>Favorite Foods:</strong4> <%= @account.profile.favorite_foods %></li>
        </ul>
      <h2>Order Info:</h2>
        <ul>
          <li><strong>Name:</strong> <%= @ord.name %></li>
          <li><strong>Order Address:</strong> <%= @ord.address %></li>
          <li><strong>Any Dietary Preferences?</strong> <%= @ord.dietary_preferences %></li>
          <li><strong>Reason for Event:</strong> <%= @ord.reason_for_event %></li>
        </ul>
     </div>

app/views/confirmer/welcome.html.erb
    <div width = "390px" height = "180px" style = "background-color:#911821; border:2px solid black">
      <%= image_tag 'http://storage.googleapis.com/emergenchefvideo/logo.png' %>
    </div>
    <div style = "border:2px solid black; border-top:0; padding:1em">
      <h1>Hello <%= @account.username %>!</h1>
       Thank you for signing up for Emergen-Chef!  We can't wait to work with you!  Click <%= link_to 'here', "http://emergenchef.herokuapp.com#{verify_user_path(@account.id, @account.verification_token)}", {method: :patch} %> to activate your account and get started!
     </div>