config/routes.rb
EmergenChef::Application.routes.draw do
  require 'sidekiq/web'
=begin
  delete 'destroy_order' => 'orders#destroy', :as => :destroy_order_path
  post 'orders' => 'orders#create'
  update method
=end

  root 'users#welcome'
  get "about/adam" => "statics#adam", :as => :adam
  get 'sign_up' => 'users#new', :as => :new_user
  delete 'sign_out' => 'auths#destroy', :as => :auths
  get 'sign_in' => 'auths#new', :as => :new_auth
  get 'auths/resend-email/:id' => 'auths#resend_verification_email', :as => :resend
  resources :auths, only:[ :create]
  
  get 'users/:id/verify/:verification_token' => 'users#verify', :as => :verify_user
  patch 'users/:id' => 'users#update'
  resources :users, except:[:new, :update] do
    resources :orders do
    end
  end  
  
  mount Sidekiq::Web => '/sidekiq'

end

app/views/layouts/_flash.html.erb
<!-- flash.html.erb = partial to help with dismissable alerts -->


<% if flash[:error] %>
<div class='row'>
  <div id="error" class = 'col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2 alert alert-dismissable alert-warning'>

  
    <button type = "button" class = "close" data-dismiss = "alert">x
    </button>
    <strong><%= flash[:error] %></strong>
  </div>
</div>
<% elsif notice %>
<div class='row'>
  <div id = "error" class = 'col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2 alert alert-dismissable alert-success'>
    <button type = "button" class = "close" data-dismiss = "alert">x
    </button>
    <strong><%= notice %></strong>
  </div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class = "footer row">
  <div class = "text-center">&copy; 2014 by Adam Kaplan</div>
</footer>

app/views/layouts/_head.html.erb
<title>EmergenChef</title>
<%= stylesheet_link_tag "application.css", media: "all", "data-turbolinks-track" => true %>
<%= stylesheet_link_tag "http://bootswatch.com/amelia/bootstrap.min.css", media: "all", "data-turbolinks-track" => true %>
<%= stylesheet_link_tag "custom.css", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>

app/views/layouts/_header.html.erb
<header class = "row">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="/"></a>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div id="hide-xxs" class = "text-right col-md-4 pull-right corner-dock">
        <% if current_user %>
            Logged in as <%= link_to "#{current_user.username}", current_user %>
              &nbsp;|&nbsp;
          <% if is_admin? %>
            <%= link_to "Admin", users_path %>
            &nbsp;|&nbsp;
          <% end %>
            <%= link_to "Sign Out",auths_path, {:method=> :delete}  %>
              
        <% else %>
          <a data-toggle = "modal" data-target = "#signIn">Sign In</a>
          or
          <a data-toggle = "modal" data-target = "#signUp">Sign Up</a>
          &mdash; you're missing out
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href = "#">About</a></li>
          <li><a href = "#">Locations</a></li>
          <li><a href="#">Pricing</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Meet our Chefs <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Chez Adam', adam_path %></li>
              <li class = "divider"></li>
              <li><a href="#">Chez Chantilly</a></li>
              <li><a href="#">Chez Eddie</a></li>
              <li><a href="#">Chez Tiffany</a></li>
            </ul>
          </li>
        </ul>
        <div class = "text-right col-md-4 pull-right corner-dock">
          <% if current_user %>
              Logged in as <%= link_to "#{current_user.username}", current_user %>
              &nbsp;|&nbsp;
              <% if is_admin? %>
                <%= link_to "Admin", users_path %>
                &nbsp;|&nbsp;
              <% end %>
              <%= link_to 'Sign Out', auths_path, {method: :delete} %>
          <% else %>
            <a data-toggle = "modal" data-target = "#signIn">Sign In</a>
            or
            <a data-toggle = "modal" data-target = "#signUp">Sign Up</a>
            &mdash; you're missing out

          <% end %>
          
        </div>
        <div class="modal fade" id="signIn" tabindex="-1" role="dialog" aria-labelledby="signInLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-body">
                <h3>Sign In</h3>
                <!-- Form Partial for Login -->
                <%= render partial:"auths/login.html.erb" %>
              </div>
            </div>
          </div>
        </div>
        <div class="modal fade" id="signUp" tabindex="-1" role="dialog" aria-labelledby="signUpLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-body">

                <!-- Modal header/message -->
                <h3>Sign Up!</h3>

                <!-- Form Partial for Login -->
                <div>
                  <%= render partial:"users/sign_up.html.erb" %>
                </div>

                <!-- Sign-up link (redirects to users/new)-->
                <%= link_to "Sign In", new_auth_path %>
              </div>
            </div>
          </div>
        </div>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/_sign_in.html.erb
<h3>Sign In</h3>
<div>
  <%= form_for :user, {url:'/auths', method: :post} do |u| %>
    <%= u.text_field :username, class: "form-control form-group", :placeholder => "Username" %>
    <%= u.password_field :password,class: "form-control form-group", :placeholder => "Password" %>
    <div class = 'text-center'><%= u.submit "Sign In", class: " btn btn-primary" %>
    </div>
  <% end %>
</div>
Don't have an account yet? <%= link_to "Sign up!", new_user_path %>

app/views/layouts/_sign_up.html.erb
<%= form_for(User.new) do |f| %>

  <div class = "field form-group clearfix">
   <div class = "col-md-12 text-left"> <%= f.label :post, "Username" %></div>
    <div class = "col-md-12"><%= f.text_field :username, class: "form-control"%></div>
  </div>
  <div class = "form-group field clearfix">
    <div class = "text-left col-md-12"><%= f.label :post, "E-Mail Address", class: "control-label" %></div>
    <div class = "col-md-12"> <%= f.email_field :email_address, class: "form-control" %></div>
  </div>
  <div class = "field form-group clearfix">
    <div class = "text-left col-md-12"><%= f.label "Password", class: "control-label" %></div>
    <div class = "col-md-12"><%= f.password_field :password, class: "form-control" %></div>
  </div>
  <div class = "field form-group clearfix">
    <div class = "text-left col-md-12"><%= f.label :post, "Confirm Password", class: "control-label" %></div>
    <div class = "col-md-12"><%= f.password_field :password_confirmation, class: "form-control" %></div>
  </div>

  <div class = "form-group clearfix"><%= f.submit class: "col-md-4 col-md-offset-4 btn btn-primary" %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render partial: "layouts/head.html" %>
  </head>
  <body>
    <div id="container">
      <%= render partial: "layouts/header.html" %>
      <%= render partial: "layouts/flash.html" %>
      <%= yield %>
      <%= render partial: "layouts/footer.html" %>
    </div>
  </body>
</html>